language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: lucian.buzzo@gmail.com
  api_key:
    secure: KOFf0+3mO9ZGw6sdgFZvltFp4AjwavG3cY9oaBkkzRXCW9IMxeMUUYe0iXv821JEI4qlp7l3N2v8JCAYhbclwCfaRjf/EKA3AYMxtOD4F7l77kjZlbvfwCZVQLOgcHrS1+47TC1JQV9qbcaYj1DYvjt58vajxedcct1VN3rgdLzvqsnDMQ1IAMK6kJHgBucRICcNU03f3iG4Xq8YuirNi84QunbGZxynrl9SuBn00bvEL7K+qQUxa7aY5+qew9id1QkXqU/6l1CbA9MGJJDZCKVx19s4ZYRI50jRffVSKUPpdnXKeGbAK713w4IMw9FBMzCaS7Me0pZrAqKo9e9P0pmB657mPkRRU70gdv4YYioDCnTT7jqHs043ZLUdJTLcnN859VO8nRq2KwKcXtVki/Eghik89o2/LqCJBsq+MRT/bclj76Lc2yZenVpQWHuxOQwTfDIocbcbF+RnSYgw7M/6YrebzJZxd+nylC7HwxijdWFfPyIJThbD29zYVO8Ru/IVJvQG2nEptoOYOWV+LefriumUZZNbdbOVES3xcUyi3KOM2VhlH8AzrvfATRHwYrq2j01Xfyx3Q+ISeYVSZgntPZiEFDv+NrqxHu9gMkjfF/PLhcHrWgSJX0dDTIQw8+PyqyC2YDGY+Y/n7i2newK7FWm1jenBRn3wQ3Tvf9I=
  on:
    tags: true
    repo: LucianBuzzo/sound-synthesizer
